branch-defaults:
  main:
    environment: marlinsurf-environment
    group_suffix: null
global:
  application_name: marlin.surf
  branch: null
  default_ec2_keyname: marlin-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: marlin
  repository: null
  sc: git
  workspace_type: Application
